workflows:
  aarambh-workflow:
    name: Aarambh Classes Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      android: latest
    scripts:
      - name: Setup Flutter project
        script: |
          flutter create .
          cp -r assets lib web pubspec.yaml .
      - name: Set app display name
        script: |
          flutter pub global activate rename
          flutter pub global run rename --appname "Aarambh Classes"
      - name: Get dependencies
        script: flutter pub get
      - name: Generate app icons
        script: flutter pub run flutter_launcher_icons
      - name: Build Android APK
        script: flutter build apk --release
      - name: Build Android AppBundle
        script: flutter build appbundle --release
      - name: Build iOS
        script: flutter build ios --release --no-codesign
      - name: Build Web
        script: flutter build web --release
      - name: Deploy to Firebase Hosting
        script: |
          if [ -n "$FIREBASE_TOKEN" ]; then
            npm install -g firebase-tools
            firebase deploy --only hosting --token $FIREBASE_TOKEN
          else
            echo "Skipping Firebase deploy. Add FIREBASE_TOKEN in Codemagic env."
          fi
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/ios/ipa
      - build/web
